name: Build and push Docker image

on:
  push:
    branches:
      - master

jobs:
  docker:
    strategy:
      matrix:
          node_version: [12, 14, 16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-contexts: node_version=\'${{ matrix.node_version }}\'
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: djoh/nodejs-bash:${{ matrix.node_version }}